// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: scraper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataProcessor_StreamProducts_FullMethodName = "/scraper.DataProcessor/StreamProducts"
)

// DataProcessorClient is the client API for DataProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataProcessorClient interface {
	// Client-side streaming: Η Node στέλνει πολλά, η Go απαντάει μία φορά στο τέλος.
	StreamProducts(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ProductRequest, SummaryResponse], error)
}

type dataProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewDataProcessorClient(cc grpc.ClientConnInterface) DataProcessorClient {
	return &dataProcessorClient{cc}
}

func (c *dataProcessorClient) StreamProducts(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ProductRequest, SummaryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataProcessor_ServiceDesc.Streams[0], DataProcessor_StreamProducts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProductRequest, SummaryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataProcessor_StreamProductsClient = grpc.ClientStreamingClient[ProductRequest, SummaryResponse]

// DataProcessorServer is the server API for DataProcessor service.
// All implementations must embed UnimplementedDataProcessorServer
// for forward compatibility.
type DataProcessorServer interface {
	// Client-side streaming: Η Node στέλνει πολλά, η Go απαντάει μία φορά στο τέλος.
	StreamProducts(grpc.ClientStreamingServer[ProductRequest, SummaryResponse]) error
	mustEmbedUnimplementedDataProcessorServer()
}

// UnimplementedDataProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataProcessorServer struct{}

func (UnimplementedDataProcessorServer) StreamProducts(grpc.ClientStreamingServer[ProductRequest, SummaryResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamProducts not implemented")
}
func (UnimplementedDataProcessorServer) mustEmbedUnimplementedDataProcessorServer() {}
func (UnimplementedDataProcessorServer) testEmbeddedByValue()                       {}

// UnsafeDataProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataProcessorServer will
// result in compilation errors.
type UnsafeDataProcessorServer interface {
	mustEmbedUnimplementedDataProcessorServer()
}

func RegisterDataProcessorServer(s grpc.ServiceRegistrar, srv DataProcessorServer) {
	// If the following call panics, it indicates UnimplementedDataProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataProcessor_ServiceDesc, srv)
}

func _DataProcessor_StreamProducts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataProcessorServer).StreamProducts(&grpc.GenericServerStream[ProductRequest, SummaryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataProcessor_StreamProductsServer = grpc.ClientStreamingServer[ProductRequest, SummaryResponse]

// DataProcessor_ServiceDesc is the grpc.ServiceDesc for DataProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scraper.DataProcessor",
	HandlerType: (*DataProcessorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProducts",
			Handler:       _DataProcessor_StreamProducts_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "scraper.proto",
}
